- name: Ensure users exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell: /bin/bash
  loop: "{{ sshd_users }}"

- name: Create .ssh directory for users
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0700"
  loop: "{{ sshd_users }}"

- name: Deploy authorized_keys for users
  ansible.builtin.authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    state: present
  loop: "{{ sshd_users | subelements('ssh_keys') }}"

- name: Ensure /etc/ssh/sshd_config has PermitRootLogin no
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
    backup: yes
  notify: restart sshd
- name: Ensure PasswordAuthentication is disabled
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    backup: yes
  notify: restart sshd
